const categories = [
  { slug: 'general-discussion', name: 'General Discussion', icon: 'forum', description: 'Open conversation, announcements, and community chatter.' },
  { slug: 'introductions', name: 'Introductions', icon: 'waving_hand', description: 'Meet new members and share who you are.' },
  { slug: 'news-trends', name: 'News & Trends', icon: 'newspaper', description: 'Industry updates, launches, and hot takes.' },
  { slug: 'tech-support', name: 'Tech Support', icon: 'build_circle', description: 'Get help troubleshooting hardware and software.' },
  { slug: 'web-development', name: 'Web Development', icon: 'code', description: 'Frontend, backend, and full-stack web topics.' },
  { slug: 'mobile-apps', name: 'Mobile Apps', icon: 'smartphone', description: 'iOS, Android, cross-platform, and mobile UX.' },
  { slug: 'gaming', name: 'Gaming', icon: 'stadia_controller', description: 'Game reviews, clips, guides, and community events.' },
  { slug: 'esports', name: 'Esports', icon: 'emoji_events', description: 'Tournaments, teams, streams, and analysis.' },
  { slug: 'movies-tv', name: 'Movies & TV', icon: 'movie', description: 'Film trailers, breakdowns, and recommendations.' },
  { slug: 'music-audio', name: 'Music & Audio', icon: 'graphic_eq', description: 'Albums, production, podcasts, and playlists.' },
  { slug: 'photography', name: 'Photography', icon: 'photo_camera', description: 'Photos, editing tips, and creative challenges.' },
  { slug: 'design-ux', name: 'Design & UX', icon: 'palette', description: 'Branding, UI systems, and design critique.' },
  { slug: 'animation-vfx', name: 'Animation & VFX', icon: 'auto_awesome', description: 'Motion graphics, 3D, and effects workflows.' },
  { slug: 'ai-ml', name: 'AI & Machine Learning', icon: 'psychology', description: 'Models, prompts, and practical applications.' },
  { slug: 'data-science', name: 'Data Science', icon: 'bar_chart', description: 'Analysis, visualization, and experimentation.' },
  { slug: 'cybersecurity', name: 'Cybersecurity', icon: 'shield', description: 'Security news, tools, and ethical hacking.' },
  { slug: 'crypto-blockchain', name: 'Crypto & Blockchain', icon: 'currency_bitcoin', description: 'Web3 projects, market discussion, and safety.' },
  { slug: 'business-startups', name: 'Business & Startups', icon: 'rocket_launch', description: 'Growth, strategy, and founder journeys.' },
  { slug: 'marketing-social', name: 'Marketing & Social', icon: 'campaign', description: 'SEO, content strategy, and social growth.' },
  { slug: 'productivity', name: 'Productivity', icon: 'checklist', description: 'Workflows, routines, and focus systems.' },
  { slug: 'career-jobs', name: 'Career & Jobs', icon: 'work', description: 'Resume advice, interviews, and role openings.' },
  { slug: 'education-learning', name: 'Education & Learning', icon: 'school', description: 'Study resources, tutorials, and bootcamps.' },
  { slug: 'science-space', name: 'Science & Space', icon: 'science', description: 'Research updates and science explainers.' },
  { slug: 'health-fitness', name: 'Health & Fitness', icon: 'fitness_center', description: 'Training logs, nutrition, and wellness.' },
  { slug: 'mental-wellbeing', name: 'Mental Wellbeing', icon: 'self_improvement', description: 'Mindfulness, resilience, and support.' },
  { slug: 'food-cooking', name: 'Food & Cooking', icon: 'restaurant', description: 'Recipes, food photography, and reviews.' },
  { slug: 'travel-lifestyle', name: 'Travel & Lifestyle', icon: 'flight', description: 'Trip journals, planning tips, and vlogs.' },
  { slug: 'fashion-style', name: 'Fashion & Style', icon: 'checkroom', description: 'Outfits, trends, and style inspiration.' },
  { slug: 'cars-motors', name: 'Cars & Motors', icon: 'directions_car', description: 'Builds, track days, and maintenance guides.' },
  { slug: 'sports-outdoors', name: 'Sports & Outdoors', icon: 'sports_soccer', description: 'Highlights, gear, and event talk.' },
  { slug: 'books-writing', name: 'Books & Writing', icon: 'menu_book', description: 'Reading clubs, writing drafts, and critique.' },
  { slug: 'art-crafts', name: 'Art & Crafts', icon: 'brush', description: 'Illustration, DIY projects, and tutorials.' },
  { slug: 'memes-fun', name: 'Memes & Fun', icon: 'sentiment_very_satisfied', description: 'Lightweight humor and off-topic fun.' },
  { slug: 'marketplace', name: 'Marketplace', icon: 'storefront', description: 'Buy/sell/trade posts and creator shops.' },
  { slug: 'feedback-requests', name: 'Feedback Requests', icon: 'rate_review', description: 'Share work-in-progress and request critique.' },
  { slug: 'site-updates', name: 'Site Updates', icon: 'system_update_alt', description: 'Platform roadmap, changelog, and announcements.' }
];

const forumTopics = [
  'Beginner Question',
  'Showcase',
  'Project Breakdown',
  'Tutorial',
  'Resource List',
  'Weekly Challenge',
  'Hot Take',
  'Case Study',
  'Gear Review',
  'Setup Tour',
  'Feature Request',
  'Bug Report',
  'Community Poll',
  'AMA',
  'Collaboration Request',
  'Hiring',
  'Looking for Team',
  'Quick Tip',
  'Deep Dive',
  'Best Practices',
  'Roadmap Update',
  'Release Notes',
  'Event Recap',
  'Conference Notes',
  'Interview Prep',
  'Portfolio Feedback',
  'Template Share',
  'Prompt Pack',
  'Before & After',
  'Challenge Entry',
  'Streaming Schedule',
  'Podcast Episode',
  'Video Essay',
  'Short Film',
  'Album Drop',
  'Photo Dump',
  'Clip Highlights',
  'Patch Notes',
  'Tournament Talk',
  'Fan Theory',
  'Unboxing',
  'Opinion Thread',
  'Monthly Roundup',
  'Help Wanted',
  'Solved'
];

module.exports = {
  categories,
  forumTopics
};
